### ISSUE TITLE
Wrong bucket name in config.yaml

### ISSUE THREAD

**Issue by gmcfall** [konigio/konig#1353]
The config.yaml file for the gbi-uk project contains the following resource:
```
- name: "bucket-pearson-edw-batch-inbound-dev"
  type: "storage.v1.bucket"
  properties:
    name: "pearson-edw-batch-inbound-dev"
```

I expected the name within properties `pearson-edw-batch-inbound-dev` to be the name of the bucket, but instead it uses the resource name `bucket-pearson-edw-batch-inbound-dev`.

Is this a bug in deployment manager?  At any rate, we need to fix it.
