### ISSUE TITLE
Nested Record Transform via Inverse Path

### ISSUE THREAD

**Issue by gmcfall** [konigio/konig#1411]
I want a Dataflow pipeline that can construct a transform based on an inverse path in the KQL formula.

For example, suppose I have the following source shapes:

*PersonNameSourceShape*
```
id: http://example.com/person/alice
first_name: Alice
```

*AddressSourceShape*
```
address_of: http://example.com/person/alice
city: Springfield
state: VA
```

And we want to transform to the following target shape:

*PersonTargetShape*
```
id: http://example.com/person/alice
givenName: Alice
postalAddress:
   addressLocality: Springfield
   addressRegion: VA
```

Suppose further that the `address_of` property is mapped via the following formula:

```
   $^address
```

So, in this case, we have not defined `address_of` to be the `owl:inverseOf`.  Instead, we have used a KQL formula which says that it is the inverse in the context of the source shape  (rather than globally).
