### ISSUE TITLE
config.yaml file has the field errorId multiple times for the error tables

### ISSUE THREAD

**Issue by Uvashriamm** [konigio/konig#1558]
The schema for the error table has errorId multiple times and it should be replace with errorMessage

```
    schema:
      fields:
      - mode: "REQUIRED"
        name: "errorId"
        type: "STRING"
      - description: "A timestamp that records when the error record was created"
        mode: "REQUIRED"
        name: "errorCreated"
        type: "TIMESTAMP"
      - description: "A UUID that uniquely identifies the error record"
        mode: "REQUIRED"
        name: "errorId"
        type: "STRING"
      - description: "The Job Name for the ETL pipeline"
        mode: "REQUIRED"
        name: "pipelineJobName"
        type: "STRING"
```
