### ISSUE TITLE
Generate Data Services configuration file

### ISSUE THREAD

**Issue by gmcfall** [konigio/konig#452]
I want a maven plugin that automatically generates the configuration file for Data Services.
This is a YAML file like...

```
  container:
    - slug: person
      extentClass: http://schema.org/Person
      defaultShape: http://example.com/shapes/PersonShape
    - slug: product
      extentClass: http://schema.org/Product
      defaultShape: http://example.com/shapes/ProductShape
```
