### ISSUE TITLE
YAML Reader should support inline object properties in a list

### ISSUE THREAD

**Issue by gmcfall** [konigio/konig#453]
YAML Reader should support lists like this...

```
somelist:
  - name: foo
    description: A sample Foo object
  - name: bar
    description: A sample Bar object
```
